import { CoverLetterData, createEmptyCoverLetter } from '@/types/cover-letter';
import { ColorSchemeId } from '@/types/cv';
import { FunctieExample } from '@/lib/cv-examples/types';

/**
 * Per-function letter context for the Swedish market. The actual letter
 * body is generated by combining this with the CV example's persona data — so
 * we get realistic letters for every function without hand-writing 20 variants.
 */
interface LetterContext {
  /** Target vacancy title (often slightly different from the candidate's current role) */
  vacancyTitle: string;
  /** Fictional Swedish company they're applying to */
  recipientCompany: string;
  recipientCity: string;
  /** Optional contact person */
  contactName?: string;
  /** Hooks to weave into the body — concrete to the function */
  hookA: string;
  hookB: string;
  /** Optional availability statement */
  availability?: string;
}

const LETTER_CONTEXTS_SV: Record<string, LetterContext> = {
  developer: {
    vacancyTitle: 'Senior Backend Engineer',
    recipientCompany: 'Spotify',
    recipientCity: 'Stockholm',
    hookA: 'att bygga tillförlitlig betalningsinfrastruktur',
    hookB: 'att mentorera juniora utvecklare och bidra till code review-guidelines',
  },
  verpleegkundige: {
    vacancyTitle: 'IVA-sjuksköterska',
    recipientCompany: 'Karolinska Universitetssjukhuset',
    recipientCity: 'Stockholm',
    hookA: 'omvårdnad av postoperativa patienter efter hjärtkirurgi',
    hookB: 'handledning av sjuksköterskestudenter och bidrag till kvalitetsarbete',
  },
  leraar: {
    vacancyTitle: 'Ämneslärare Historia (gy 1-3)',
    recipientCompany: 'Östra Real gymnasium',
    recipientCity: 'Stockholm',
    hookA: 'undervisning i historia på gymnasiet',
    hookB: 'mentorskap i gymnasiets högre årskurser och bidrag till kursplaneutveckling',
  },
  accountant: {
    vacancyTitle: 'Audit Manager Financial Services',
    recipientCompany: 'PwC Sverige',
    recipientCity: 'Stockholm',
    hookA: 'att leda revisionsuppdrag hos banker och försäkringsbolag',
    hookB: 'att coacha associates mot Revisorsexamen',
  },
  'marketing-manager': {
    vacancyTitle: 'Senior Marketing Manager Demand Gen',
    recipientCompany: 'Klarna',
    recipientCity: 'Stockholm',
    hookA: 'att sänka Customer Acquisition Cost inom B2B SaaS',
    hookB: 'att leda ett team av demand-generation-specialister',
  },
  verkoper: {
    vacancyTitle: 'Senior Account Executive Enterprise',
    recipientCompany: 'HubSpot Nordics',
    recipientCity: 'Stockholm',
    hookA: 'att stänga multi-stakeholder enterprise-affärer',
    hookB: 'att bygga en outbound playbook för en ny nisch',
  },
  'office-manager': {
    vacancyTitle: 'Office Manager',
    recipientCompany: 'IKEA',
    recipientCity: 'Älmhult',
    hookA: 'att driva ett huvudkontor och en intensiv ledningskalender',
    hookB: 'att onboarda nya medarbetare och leverantörshantering',
  },
  projectmanager: {
    vacancyTitle: 'Senior Project Manager Digital Transformation',
    recipientCompany: 'SEB',
    recipientCity: 'Stockholm',
    hookA: 'att leda program kring core banking och plattformsmodernisering',
    hookB: 'styrgruppshantering på ledningsnivå',
  },
  stagiair: {
    vacancyTitle: 'Strategy Intern',
    recipientCompany: 'McKinsey & Company',
    recipientCity: 'Stockholm',
    hookA: 'min erfarenhet som ordförande för en studentförening med 560 medlemmar',
    hookB: 'mina case-tävlingsresultat och min betygsprognos',
    availability: 'Tillgänglig för 5 månaders praktik från februari 2026.',
  },
  consultant: {
    vacancyTitle: 'Engagement Manager',
    recipientCompany: 'Bain & Company',
    recipientCity: 'Stockholm',
    hookA: 'att leda PMI-uppdrag och kostnadstransformationsprogram',
    hookB: 'att coacha associates mot befordran',
  },
  'logistiek-medewerker': {
    vacancyTitle: 'Senior Lagerarbetare',
    recipientCompany: 'PostNord',
    recipientCity: 'Rosersberg',
    hookA: 'att arbeta i högt tempo i distributionscentraler med WMS-system',
    hookB: 'skiftcoachansvar och cykelinventering',
  },
  monteur: {
    vacancyTitle: 'Senior Servicetekniker',
    recipientCompany: 'Bravida',
    recipientCity: 'Västerås',
    hookA: 'att installera gaspannor, värmepumpar och hybridvärmesystem',
    hookB: 'att vara första kontakten för kunder och kollegor på regionala uppdrag',
  },
  'horeca-medewerker': {
    vacancyTitle: 'Skiftledare Service',
    recipientCompany: 'PM & Vänner',
    recipientCity: 'Växjö',
    hookA: 'fine dining-service på Michelin-nivå',
    hookB: 'vinpairing-rådgivning och servering av internationell klientel',
  },
  'data-analist': {
    vacancyTitle: 'Senior Data Analyst',
    recipientCompany: 'Spotify',
    recipientCity: 'Stockholm',
    hookA: 'att bygga prognosdashboards som används direkt för affärsbeslut',
    hookB: 'A/B-testanalys och modernisering av datapipelines via dbt',
  },
  'hr-manager': {
    vacancyTitle: 'HR Manager Sverige',
    recipientCompany: 'H&M Group',
    recipientCity: 'Stockholm',
    hookA: 'fullständigt ägarskap av HR-cykeln inom scale-ups och mellansegmentet',
    hookB: 'mätbar sänkning av personalomsättning genom redesign av onboarding',
  },
  'verzorgende-ig': {
    vacancyTitle: 'Senior undersköterska — Demensavdelning',
    recipientCompany: 'Attendo',
    recipientCity: 'Malmö',
    hookA: 'att vara lead-undersköterska för boende med demens i småskaliga enheter',
    hookB: 'att mentorera undersköterskelärlingar och bidra till kvalitetskommittéer',
  },
  designer: {
    vacancyTitle: 'Senior Product Designer',
    recipientCompany: 'Klarna',
    recipientCity: 'Stockholm',
    hookA: 'att designa och äga ett designsystem som används av dussintals engineers',
    hookB: 'att driva användarforskning och validera designbeslut med konverteringsdata',
  },
  'financieel-medewerker': {
    vacancyTitle: 'Ekonomiassistent',
    recipientCompany: 'SAS Scandinavian Airlines',
    recipientCity: 'Stockholm',
    hookA: 'hela kundreskontran och leverantörsreskontran i mindre och medelstora företag',
    hookB: 'stöd vid årsbokslut och automatisering av fakturahantering',
  },
  'klantenservice-medewerker': {
    vacancyTitle: 'Senior Kundtjänstmedarbetare',
    recipientCompany: 'Elgiganten Kundtjänst',
    recipientCity: 'Stockholm',
    hookA: 'att uppnå NPS- och First-Contact-Resolution-poäng över snittet',
    hookB: 'att coacha nya kollegor under deras introduktionsperiod',
  },
  recruiter: {
    vacancyTitle: 'Senior Talent Acquisition Partner',
    recipientCompany: 'Spotify',
    recipientCity: 'Stockholm',
    hookA: 'sourcing av seniora mjukvaruingenjörer och dataspecialister',
    hookB: 'sänkning av time-to-hire genom starkare hiring manager-partnerskap',
  },
};

/**
 * Build a CoverLetterData object from a CV example, using the per-function
 * Swedish letter context. The candidate's name, address, and contact info come
 * from the CV example; the letter body is composed from the hooks plus a
 * generic Swedish-language structure.
 */
export function buildExampleLetter(example: FunctieExample): CoverLetterData {
  const ctx = LETTER_CONTEXTS_SV[example.slug];
  if (!ctx) return createEmptyCoverLetter();

  const now = new Date('2026-05-15').toISOString();
  const greeting = ctx.contactName ? `Bästa ${ctx.contactName},` : 'Bästa rekryterare,';

  const opening = `Jag skriver för att uttrycka mitt starka intresse för rollen som ${ctx.vacancyTitle} hos ${ctx.recipientCompany}. Kombinationen av er organisation och denna position stämmer väl överens med den riktning jag vill ta min karriär.`;

  const body = `I min nuvarande roll som ${example.cv.experience[0]?.jobTitle ?? 'specialist'}${
    example.cv.experience[0]?.company ? ` på ${example.cv.experience[0].company}` : ''
  } har jag fått erfarenhet av ${ctx.hookA}. Vid sidan av det fokuserar jag aktivt på ${ctx.hookB} — för mig är det en väsentlig del av arbetet. I annonsen från ${ctx.recipientCompany} känner jag igen hur dessa element kommer samman.`;

  const closing = `${
    ctx.availability ?? 'Jag tar gärna ett samtal för att diskutera min ansökan vidare.'
  } Du når mig på ${example.cv.personal.email}${
    example.cv.personal.phone ? ` eller på ${example.cv.personal.phone}` : ''
  }.`;

  return {
    id: `example-letter-${example.slug}`,
    createdAt: now,
    updatedAt: now,
    sender: {
      firstName: example.cv.personal.firstName,
      lastName: example.cv.personal.lastName,
      email: example.cv.personal.email,
      phone: example.cv.personal.phone,
      address: example.cv.personal.address || '',
      city: example.cv.personal.city,
      postalCode: example.cv.personal.postalCode || '',
    },
    recipient: {
      contactName: ctx.contactName ?? '',
      contactTitle: '',
      company: ctx.recipientCompany,
      city: ctx.recipientCity,
    },
    vacancyTitle: ctx.vacancyTitle,
    vacancyReference: '',
    date: '2026-05-15',
    letterCity: example.cv.personal.city,
    greeting,
    opening,
    body,
    closing,
    signature: 'Med vänlig hälsning,',
    meta: {
      selectedTemplate: 'modern',
      selectedColorScheme: (example.colorSchemeId as ColorSchemeId) || 'emerald',
    },
  };
}

export function hasLetterContext(slug: string): boolean {
  return slug in LETTER_CONTEXTS_SV;
}

export { LETTER_CONTEXTS_SV };
