import { CoverLetterData, createEmptyCoverLetter } from '@/types/cover-letter';
import { ColorSchemeId } from '@/types/cv';
import { FunctieExample } from '@/lib/cv-examples/types';

/**
 * Per-function letter context for the German (DACH) market. The actual letter
 * body is generated by combining this with the CV example's persona data — so
 * we get realistic letters for every function without hand-writing 20 variants.
 */
interface LetterContext {
  /** Target vacancy title (often slightly different from the candidate's current role) */
  vacancyTitle: string;
  /** Fictional DACH company they're applying to */
  recipientCompany: string;
  recipientCity: string;
  /** Optional contact person */
  contactName?: string;
  /** Hooks to weave into the body — concrete to the function */
  hookA: string;
  hookB: string;
  /** Optional availability statement */
  availability?: string;
}

const LETTER_CONTEXTS_DE: Record<string, LetterContext> = {
  developer: {
    vacancyTitle: 'Senior Backend Engineer',
    recipientCompany: 'N26',
    recipientCity: 'Berlin',
    hookA: 'dem Aufbau zuverlässiger Zahlungsinfrastruktur',
    hookB: 'dem Mentoring von Junior-Entwicklern und der Mitarbeit an Code-Review-Guidelines',
  },
  verpleegkundige: {
    vacancyTitle: 'Intensivpflegerin',
    recipientCompany: 'Charité Berlin',
    recipientCity: 'Berlin',
    hookA: 'der Versorgung postoperativer Patienten der Herzchirurgie',
    hookB: 'der Praxisanleitung von Pflegeauszubildenden und der Mitarbeit an Qualitätsverbesserung',
  },
  leraar: {
    vacancyTitle: 'Lehrer Geschichte (Sek. II)',
    recipientCompany: 'Humboldt-Gymnasium Berlin',
    recipientCity: 'Berlin',
    hookA: 'dem Unterricht in der gymnasialen Oberstufe',
    hookB: 'der Klassenleitung in der Oberstufe und dem Beitrag zur Curriculumentwicklung',
  },
  accountant: {
    vacancyTitle: 'Audit Manager Financial Services',
    recipientCompany: 'PwC Deutschland',
    recipientCity: 'Frankfurt am Main',
    hookA: 'der Leitung von Prüfungsmandaten bei Banken und Versicherern',
    hookB: 'dem Coaching von Associates Richtung WP-Examen',
  },
  'marketing-manager': {
    vacancyTitle: 'Senior Marketing Manager Demand Gen',
    recipientCompany: 'Klarna DACH',
    recipientCity: 'Berlin',
    hookA: 'der Senkung der Customer Acquisition Cost im B2B-SaaS',
    hookB: 'der Führung eines Teams aus Demand-Gen-Spezialisten',
  },
  verkoper: {
    vacancyTitle: 'Senior Account Executive Enterprise',
    recipientCompany: 'HubSpot DACH',
    recipientCity: 'Berlin',
    hookA: 'dem Closing von Multi-Stakeholder-Enterprise-Deals',
    hookB: 'dem Aufbau eines Outbound-Playbooks für eine neue Nische',
  },
  'office-manager': {
    vacancyTitle: 'Office Manager',
    recipientCompany: 'Trivago',
    recipientCity: 'Düsseldorf',
    hookA: 'der Steuerung eines Hauptsitz-Betriebs und einer dichten Geschäftsführungs-Agenda',
    hookB: 'dem Onboarding neuer Mitarbeitender und dem Vendor-Management',
  },
  projectmanager: {
    vacancyTitle: 'Senior Project Manager Digital Transformation',
    recipientCompany: 'Commerzbank',
    recipientCity: 'Frankfurt am Main',
    hookA: 'der Leitung von Programmen rund um Core-Banking-Modernisierung',
    hookB: 'dem Lenkungsausschuss-Management auf Vorstandsebene',
  },
  stagiair: {
    vacancyTitle: 'Strategy Intern',
    recipientCompany: 'McKinsey & Company',
    recipientCity: 'München',
    hookA: 'meiner Erfahrung als Vorsitzende einer Studierendeninitiative mit 560 Mitgliedern',
    hookB: 'meinen Case-Competition-Ergebnissen und meinem Honors-Track',
    availability: 'Verfügbar für ein 5-monatiges Praktikum ab Februar 2026.',
  },
  consultant: {
    vacancyTitle: 'Engagement Manager',
    recipientCompany: 'Bain & Company',
    recipientCity: 'München',
    hookA: 'der Leitung von PMI-Projekten und Cost-Transformation-Programmen',
    hookB: 'dem Coaching von Associates Richtung Beförderung',
  },
  'logistiek-medewerker': {
    vacancyTitle: 'Senior Lagermitarbeiter',
    recipientCompany: 'Deutsche Post DHL',
    recipientCity: 'Bonn',
    hookA: 'dem Arbeiten im hohen Tempo in Distributionszentren mit WMS-Systemen',
    hookB: 'der Shift-Coach-Verantwortung und zyklischen Inventur',
  },
  monteur: {
    vacancyTitle: 'Anlagenmechaniker SHK',
    recipientCompany: 'Vaillant Service',
    recipientCity: 'Remscheid',
    hookA: 'der Installation von Heizungsanlagen, Wärmepumpen und Hybrid-Systemen',
    hookB: 'dem Erstkontakt für Kunden und Kollegen im regionalen Service',
  },
  'horeca-medewerker': {
    vacancyTitle: 'Schichtleiter Service',
    recipientCompany: 'Hotel Sacher',
    recipientCity: 'Wien',
    hookA: 'dem Fine-Dining-Service auf Sterne-Niveau',
    hookB: 'der Wein-Pairing-Beratung und der Bedienung internationaler Klientel',
  },
  'data-analist': {
    vacancyTitle: 'Senior Data Analyst',
    recipientCompany: 'Zalando',
    recipientCity: 'Berlin',
    hookA: 'dem Aufbau von Forecasting-Dashboards, die direkt für Business-Entscheidungen genutzt werden',
    hookB: 'der A/B-Test-Analyse und der Modernisierung von Daten-Pipelines via dbt',
  },
  'hr-manager': {
    vacancyTitle: 'HR Manager DACH',
    recipientCompany: 'Lufthansa Group',
    recipientCity: 'Frankfurt am Main',
    hookA: 'der vollständigen Ownership des HR-Cycles in Scale-ups und Mid-Market',
    hookB: 'der messbaren Senkung der Mitarbeiterfluktuation durch Onboarding-Redesign',
  },
  'verzorgende-ig': {
    vacancyTitle: 'Bezugspflegekraft Psychogeriatrie',
    recipientCompany: 'Caritas Sachsen',
    recipientCity: 'Dresden',
    hookA: 'der Bezugspflege für Bewohner mit Demenz in kleinen Wohngruppen',
    hookB: 'der Praxisanleitung von Auszubildenden der Altenpflege und der Mitarbeit in Qualitätskommissionen',
  },
  designer: {
    vacancyTitle: 'Senior Product Designer',
    recipientCompany: 'N26',
    recipientCity: 'Berlin',
    hookA: 'dem Entwurf und der Ownership eines Design Systems, das von dutzenden Engineers genutzt wird',
    hookB: 'der Durchführung von User Research und der Validierung von Design-Entscheidungen über Conversion-Daten',
  },
  'financieel-medewerker': {
    vacancyTitle: 'Finanzbuchhalter',
    recipientCompany: 'Lufthansa Group',
    recipientCity: 'Frankfurt am Main',
    hookA: 'der vollständigen Debitoren- und Kreditorenbuchhaltung im Mittelstand',
    hookB: 'der Unterstützung beim Jahresabschluss und der Automatisierung der Rechnungsverarbeitung',
  },
  'klantenservice-medewerker': {
    vacancyTitle: 'Senior Kundenberater',
    recipientCompany: 'Lufthansa Customer Care',
    recipientCity: 'Frankfurt am Main',
    hookA: 'dem Erzielen überdurchschnittlicher NPS- und First-Contact-Resolution-Werte',
    hookB: 'der Praxisanleitung neuer Kollegen während der Einarbeitungsphase',
  },
  recruiter: {
    vacancyTitle: 'Senior Talent Acquisition Partner',
    recipientCompany: 'SAP',
    recipientCity: 'Walldorf',
    hookA: 'dem Sourcing von Senior Software Engineers und Data Professionals',
    hookB: 'der Verringerung der Time-to-Hire durch stärkere Hiring-Manager-Partnership',
  },
};

/**
 * Build a CoverLetterData object from a CV example, using the per-function
 * German letter context. The candidate's name, address, and contact info come
 * from the CV example; the letter body is composed from the hooks plus a
 * generic formal German structure.
 */
export function buildExampleLetter(example: FunctieExample): CoverLetterData {
  const ctx = LETTER_CONTEXTS_DE[example.slug];
  if (!ctx) return createEmptyCoverLetter();

  const now = new Date('2026-05-15').toISOString();
  const greeting = ctx.contactName
    ? `Sehr geehrte/r Frau/Herr ${ctx.contactName},`
    : 'Sehr geehrte Damen und Herren,';

  const opening = `mit großem Interesse habe ich Ihre Stellenausschreibung für die Position als ${ctx.vacancyTitle} bei ${ctx.recipientCompany} gelesen. Die Kombination aus Ihrem Unternehmen und dieser Funktion passt hervorragend zu der Richtung, in die ich meine Karriere weiterentwickeln möchte.`;

  const body = `In meiner aktuellen Position als ${example.cv.experience[0]?.jobTitle ?? 'Fachkraft'}${
    example.cv.experience[0]?.company ? ` bei ${example.cv.experience[0].company}` : ''
  } konnte ich umfangreiche Erfahrung in ${ctx.hookA} sammeln. Darüber hinaus widme ich mich aktiv ${ctx.hookB} — für mich ist dies ein unverzichtbarer Bestandteil der Tätigkeit. In der Stellenausschreibung von ${ctx.recipientCompany} erkenne ich genau die Art und Weise, wie diese Elemente zusammenkommen.`;

  const closing = `${
    ctx.availability ?? 'Gerne erläutere ich Ihnen meine Motivation in einem persönlichen Gespräch.'
  } Sie erreichen mich unter ${example.cv.personal.email}${
    example.cv.personal.phone ? ` oder telefonisch unter ${example.cv.personal.phone}` : ''
  }.`;

  return {
    id: `example-letter-${example.slug}`,
    createdAt: now,
    updatedAt: now,
    sender: {
      firstName: example.cv.personal.firstName,
      lastName: example.cv.personal.lastName,
      email: example.cv.personal.email,
      phone: example.cv.personal.phone,
      address: example.cv.personal.address || '',
      city: example.cv.personal.city,
      postalCode: example.cv.personal.postalCode || '',
    },
    recipient: {
      contactName: ctx.contactName ?? '',
      contactTitle: '',
      company: ctx.recipientCompany,
      city: ctx.recipientCity,
    },
    vacancyTitle: ctx.vacancyTitle,
    vacancyReference: '',
    date: '2026-05-15',
    letterCity: example.cv.personal.city,
    greeting,
    opening,
    body,
    closing,
    signature: 'Mit freundlichen Grüßen,',
    meta: {
      selectedTemplate: 'modern',
      selectedColorScheme: (example.colorSchemeId as ColorSchemeId) || 'emerald',
    },
  };
}

export function hasLetterContext(slug: string): boolean {
  return slug in LETTER_CONTEXTS_DE;
}

export { LETTER_CONTEXTS_DE };
