import { CoverLetterData, createEmptyCoverLetter } from '@/types/cover-letter';
import { ColorSchemeId } from '@/types/cv';
import { FunctieExample } from '@/lib/cv-examples/types';

/**
 * Per-functie letter context. The actual letter body is generated by combining
 * this with the CV example's persona data — so we get realistic letters for
 * every functie without hand-writing 20 variants.
 */
interface LetterContext {
  /** Target vacancy title (often slightly different from the candidate's current role) */
  vacancyTitle: string;
  /** Fictional company they're applying to */
  recipientCompany: string;
  recipientCity: string;
  /** Optional contact person */
  contactName?: string;
  /** Hooks to weave into the body — concrete to the functie */
  hookA: string;
  hookB: string;
  /** Optional availability statement */
  availability?: string;
}

const LETTER_CONTEXTS: Record<string, LetterContext> = {
  developer: {
    vacancyTitle: 'Senior Backend Engineer',
    recipientCompany: 'Mollie',
    recipientCity: 'Amsterdam',
    hookA: 'het bouwen van betrouwbare betalingsinfrastructuur',
    hookB: 'het mentoren van junior engineers en bijdragen aan code-review guidelines',
  },
  verpleegkundige: {
    vacancyTitle: 'IC-Verpleegkundige',
    recipientCompany: 'Erasmus MC',
    recipientCity: 'Rotterdam',
    hookA: 'het verzorgen van post-operatieve hartchirurgie-patiënten',
    hookB: 'het begeleiden van HBO-V studenten en bijdragen aan kwaliteitsverbetering',
  },
  leraar: {
    vacancyTitle: 'Eerstegraads Docent Geschiedenis',
    recipientCompany: 'Stedelijk Gymnasium Haarlem',
    recipientCity: 'Haarlem',
    hookA: 'het lesgeven aan havo- en vwo-bovenbouw',
    hookB: 'mentoraat in de bovenbouw en bijdrage aan curriculumontwikkeling',
  },
  accountant: {
    vacancyTitle: 'Audit Manager Financial Services',
    recipientCompany: 'PwC Nederland',
    recipientCity: 'Amsterdam',
    hookA: 'het leiden van controleopdrachten bij banken en verzekeraars',
    hookB: 'het coachen van associates richting hun RA-eindtraject',
  },
  'marketing-manager': {
    vacancyTitle: 'Senior Marketing Manager Demand Gen',
    recipientCompany: 'Adyen',
    recipientCity: 'Amsterdam',
    hookA: 'het verlagen van Customer Acquisition Cost in B2B SaaS',
    hookB: 'aansturen van een team van demand-gen specialisten',
  },
  verkoper: {
    vacancyTitle: 'Senior Account Executive Enterprise',
    recipientCompany: 'HubSpot Benelux',
    recipientCity: 'Amsterdam',
    hookA: 'het closen van multi-stakeholder enterprise-deals',
    hookB: 'het bouwen van een outbound playbook voor een nieuwe niche',
  },
  'office-manager': {
    vacancyTitle: 'Office Manager',
    recipientCompany: 'Bookings.com',
    recipientCity: 'Amsterdam',
    hookA: 'het beheren van een hoofdkantoor-operatie en een drukke directie-agenda',
    hookB: 'onboarding van nieuwe medewerkers en vendor-management',
  },
  projectmanager: {
    vacancyTitle: 'Senior Project Manager Digital Transformation',
    recipientCompany: 'ABN AMRO',
    recipientCity: 'Amsterdam',
    hookA: 'het leiden van programma\'s rond core-banking modernisatie',
    hookB: 'stuurgroep-management op directie-niveau',
  },
  stagiair: {
    vacancyTitle: 'Strategy Intern',
    recipientCompany: 'McKinsey & Company',
    recipientCity: 'Amsterdam',
    hookA: 'mijn ervaring als voorzitter van een studievereniging met 560 leden',
    hookB: 'mijn case-competition resultaten en honours-track',
    availability: 'Beschikbaar voor een 5-maanden stage vanaf februari 2026.',
  },
  consultant: {
    vacancyTitle: 'Engagement Manager',
    recipientCompany: 'Bain & Company',
    recipientCity: 'Amsterdam',
    hookA: 'het leiden van PMI-trajecten en cost-transformation programma\'s',
    hookB: 'het coachen van associates richting promotie',
  },
  'logistiek-medewerker': {
    vacancyTitle: 'Senior Logistiek Medewerker',
    recipientCompany: 'PostNL',
    recipientCity: 'Den Haag',
    hookA: 'het werken op hoog tempo in distributiecentra met WMS-systemen',
    hookB: 'shift-coach verantwoordelijkheid en cyclische voorraadtelling',
  },
  monteur: {
    vacancyTitle: 'Eerste Monteur Installatietechniek',
    recipientCompany: 'ENGIE Services',
    recipientCity: 'Utrecht',
    hookA: 'installatie van CV-ketels, warmtepompen en hybride systemen',
    hookB: 'eerstaanspreekpunt zijn voor klanten en collega\'s in regio-werk',
  },
  'horeca-medewerker': {
    vacancyTitle: 'Shift-leader Bediening',
    recipientCompany: 'The Dylan Hotel',
    recipientCity: 'Amsterdam',
    hookA: 'fine-dining bediening op Michelin-niveau',
    hookB: 'wijn-pairing advies en internationale clientèle bedienen',
  },
  'data-analist': {
    vacancyTitle: 'Senior Data Analyst',
    recipientCompany: 'Booking.com',
    recipientCity: 'Amsterdam',
    hookA: 'het bouwen van forecasting-dashboards die direct gebruikt worden voor business-beslissingen',
    hookB: 'A/B-test analyse en data-pipeline modernisatie via dbt',
  },
  'hr-manager': {
    vacancyTitle: 'HR Manager NL',
    recipientCompany: 'Coolblue',
    recipientCity: 'Rotterdam',
    hookA: 'volledige HR-cyclus eigenaarschap binnen scale-ups en mid-market',
    hookB: 'meetbare verlaging van employee turnover door onboarding-redesign',
  },
  'verzorgende-ig': {
    vacancyTitle: 'EVV\'er Psychogeriatrie',
    recipientCompany: 'ZorgGroep Apeldoorn',
    recipientCity: 'Apeldoorn',
    hookA: 'eerstverantwoordelijke zijn voor cliënten met dementie binnen kleinschalige woongroepen',
    hookB: 'werkbegeleiding van MBO-V leerlingen en bijdrage aan kwaliteitscommissies',
  },
  designer: {
    vacancyTitle: 'Senior Product Designer',
    recipientCompany: 'Bunq',
    recipientCity: 'Amsterdam',
    hookA: 'het ontwerpen en eigenaarschap van een design system gebruikt door tientallen engineers',
    hookB: 'user research uitvoeren en design-beslissingen valideren met conversie-data',
  },
  'financieel-medewerker': {
    vacancyTitle: 'Financieel Medewerker',
    recipientCompany: 'KLM Royal Dutch Airlines',
    recipientCity: 'Schiphol',
    hookA: 'de volledige debiteuren- en crediteurenadministratie binnen MKB-organisaties',
    hookB: 'ondersteuning bij jaarafsluiting en automatisering van factuurverwerking',
  },
  'klantenservice-medewerker': {
    vacancyTitle: 'Senior Klantenservice Medewerker',
    recipientCompany: 'KLM Customer Care',
    recipientCity: 'Schiphol',
    hookA: 'het behalen van bovengemiddelde NPS en First-Contact-Resolution scores',
    hookB: 'werkbegeleiding van nieuwe collega\'s tijdens hun inwerkperiode',
  },
  recruiter: {
    vacancyTitle: 'Senior Talent Acquisition Partner',
    recipientCompany: 'Booking.com',
    recipientCity: 'Amsterdam',
    hookA: 'het werven van senior software engineers en data professionals',
    hookB: 'time-to-hire verlagen via betere hiring-manager partnership',
  },
};

/**
 * Build a CoverLetterData object from a CV example, using a per-functie letter
 * context. The candidate's name, address, and contact info come from the CV
 * example; the letter body is composed from the hooks + a generic structure.
 */
export function buildExampleLetter(example: FunctieExample): CoverLetterData {
  const ctx = LETTER_CONTEXTS[example.slug];
  if (!ctx) return createEmptyCoverLetter();

  const now = new Date('2026-05-15').toISOString();
  const fullName = `${example.cv.personal.firstName} ${example.cv.personal.lastName}`.trim();
  const greeting = ctx.contactName ? `Geachte ${ctx.contactName},` : 'Geachte heer / mevrouw,';

  const opening = `Met veel interesse heb ik kennis genomen van de vacature voor ${ctx.vacancyTitle} bij ${ctx.recipientCompany}. De combinatie van uw organisatie en deze functie sluit aan op de richting waar ik mijn carrière naartoe wil ontwikkelen.`;

  const body = `In mijn huidige rol als ${example.cv.experience[0]?.jobTitle ?? 'professional'}${
    example.cv.experience[0]?.company ? ` bij ${example.cv.experience[0].company}` : ''
  } heb ik ervaring opgedaan met ${ctx.hookA}. Daarnaast richt ik me actief op ${ctx.hookB} — voor mij is dat een onmisbaar onderdeel van het vak. Ik herken in de vacaturetekst van ${ctx.recipientCompany} de manier waarop deze elementen samenkomen.`;

  const closing = `${
    ctx.availability ?? 'Ik licht mijn motivatie graag toe in een persoonlijk gesprek.'
  } U kunt mij bereiken via ${example.cv.personal.email}${
    example.cv.personal.phone ? ` of ${example.cv.personal.phone}` : ''
  }.`;

  return {
    id: `example-letter-${example.slug}`,
    createdAt: now,
    updatedAt: now,
    sender: {
      firstName: example.cv.personal.firstName,
      lastName: example.cv.personal.lastName,
      email: example.cv.personal.email,
      phone: example.cv.personal.phone,
      address: example.cv.personal.address || '',
      city: example.cv.personal.city,
      postalCode: example.cv.personal.postalCode || '',
    },
    recipient: {
      contactName: ctx.contactName ?? '',
      contactTitle: '',
      company: ctx.recipientCompany,
      city: ctx.recipientCity,
    },
    vacancyTitle: ctx.vacancyTitle,
    vacancyReference: '',
    date: '2026-05-15',
    letterCity: example.cv.personal.city,
    greeting,
    opening,
    body,
    closing,
    signature: 'Met vriendelijke groet,',
    meta: {
      selectedTemplate: 'modern',
      selectedColorScheme: (example.colorSchemeId as ColorSchemeId) || 'emerald',
    },
  };
}

export function hasLetterContext(slug: string): boolean {
  return slug in LETTER_CONTEXTS;
}
