import { CoverLetterData, createEmptyCoverLetter } from '@/types/cover-letter';
import { ColorSchemeId } from '@/types/cv';
import { FunctieExample } from '@/lib/cv-examples/types';

/**
 * Per-function letter context for the English (UK) market. The actual letter
 * body is generated by combining this with the CV example's persona data — so
 * we get realistic letters for every function without hand-writing 20 variants.
 */
interface LetterContext {
  /** Target vacancy title (often slightly different from the candidate's current role) */
  vacancyTitle: string;
  /** Fictional UK company they're applying to */
  recipientCompany: string;
  recipientCity: string;
  /** Optional contact person */
  contactName?: string;
  /** Hooks to weave into the body — concrete to the function */
  hookA: string;
  hookB: string;
  /** Optional availability statement */
  availability?: string;
}

const LETTER_CONTEXTS_EN: Record<string, LetterContext> = {
  developer: {
    vacancyTitle: 'Senior Backend Engineer',
    recipientCompany: 'Monzo Bank',
    recipientCity: 'London',
    hookA: 'building reliable payments infrastructure',
    hookB: 'mentoring junior engineers and contributing to code-review guidelines',
  },
  verpleegkundige: {
    vacancyTitle: 'ICU Nurse',
    recipientCompany: 'St Thomas\' Hospital',
    recipientCity: 'London',
    hookA: 'caring for post-operative cardiac surgery patients',
    hookB: 'supervising nursing students and contributing to quality improvement',
  },
  leraar: {
    vacancyTitle: 'History Teacher (KS3-5)',
    recipientCompany: 'Westminster School',
    recipientCity: 'London',
    hookA: 'teaching A-level History to Key Stage 5 pupils',
    hookB: 'form tutoring in the upper school and contributing to curriculum development',
  },
  accountant: {
    vacancyTitle: 'Audit Manager Financial Services',
    recipientCompany: 'PwC UK',
    recipientCity: 'London',
    hookA: 'leading audit engagements at banks and insurers',
    hookB: 'coaching associates through their final ACA exams',
  },
  'marketing-manager': {
    vacancyTitle: 'Senior Marketing Manager Demand Gen',
    recipientCompany: 'Trainline',
    recipientCity: 'London',
    hookA: 'reducing Customer Acquisition Cost in B2B SaaS',
    hookB: 'leading a team of demand-generation specialists',
  },
  verkoper: {
    vacancyTitle: 'Senior Account Executive Enterprise',
    recipientCompany: 'HubSpot UK',
    recipientCity: 'London',
    hookA: 'closing multi-stakeholder enterprise deals',
    hookB: 'building an outbound playbook for a new niche',
  },
  'office-manager': {
    vacancyTitle: 'Office Manager',
    recipientCompany: 'Wise',
    recipientCity: 'London',
    hookA: 'managing a headquarters operation and a busy executive diary',
    hookB: 'onboarding new joiners and vendor management',
  },
  projectmanager: {
    vacancyTitle: 'Senior Project Manager Digital Transformation',
    recipientCompany: 'NHS Digital',
    recipientCity: 'Leeds',
    hookA: 'leading programmes around core-banking and platform modernisation',
    hookB: 'steering committee management at executive level',
  },
  stagiair: {
    vacancyTitle: 'Strategy Intern',
    recipientCompany: 'McKinsey & Company',
    recipientCity: 'London',
    hookA: 'my experience as president of a student society with 560 members',
    hookB: 'my case-competition results and predicted First-class honours',
    availability: 'Available for a 5-month placement from February 2026.',
  },
  consultant: {
    vacancyTitle: 'Engagement Manager',
    recipientCompany: 'Bain & Company',
    recipientCity: 'London',
    hookA: 'leading PMI engagements and cost-transformation programmes',
    hookB: 'coaching associates towards promotion',
  },
  'logistiek-medewerker': {
    vacancyTitle: 'Senior Warehouse Operative',
    recipientCompany: 'Royal Mail',
    recipientCity: 'Leeds',
    hookA: 'working at pace in distribution centres with WMS systems',
    hookB: 'shift-coach responsibility and cycle counting',
  },
  monteur: {
    vacancyTitle: 'Senior Heating Engineer',
    recipientCompany: 'Octopus Energy Services',
    recipientCity: 'Bristol',
    hookA: 'installing gas boilers, heat pumps and hybrid heating systems',
    hookB: 'being the first point of contact for customers and colleagues on regional jobs',
  },
  'horeca-medewerker': {
    vacancyTitle: 'Front of House Shift Leader',
    recipientCompany: 'The Wolseley',
    recipientCity: 'London',
    hookA: 'fine-dining service at Michelin level',
    hookB: 'wine-pairing advice and serving international clientele',
  },
  'data-analist': {
    vacancyTitle: 'Senior Data Analyst',
    recipientCompany: 'Skyscanner',
    recipientCity: 'Edinburgh',
    hookA: 'building forecasting dashboards used directly for business decisions',
    hookB: 'A/B test analysis and modernising data pipelines via dbt',
  },
  'hr-manager': {
    vacancyTitle: 'HR Manager UK',
    recipientCompany: 'John Lewis Partnership',
    recipientCity: 'London',
    hookA: 'full HR cycle ownership within scale-ups and mid-market organisations',
    hookB: 'measurable reduction in employee turnover through onboarding redesign',
  },
  'verzorgende-ig': {
    vacancyTitle: 'Senior Carer — Dementia Unit',
    recipientCompany: 'Bupa Care Homes',
    recipientCity: 'Glasgow',
    hookA: 'being lead carer for residents with dementia in small-scale residential units',
    hookB: 'mentoring health and social care apprentices and contributing to quality committees',
  },
  designer: {
    vacancyTitle: 'Senior Product Designer',
    recipientCompany: 'Revolut',
    recipientCity: 'London',
    hookA: 'designing and owning a design system used by dozens of engineers',
    hookB: 'running user research and validating design decisions with conversion data',
  },
  'financieel-medewerker': {
    vacancyTitle: 'Finance Assistant',
    recipientCompany: 'British Airways',
    recipientCity: 'London',
    hookA: 'the full accounts receivable and payable function within SME organisations',
    hookB: 'supporting year-end close and automating invoice processing',
  },
  'klantenservice-medewerker': {
    vacancyTitle: 'Senior Customer Service Advisor',
    recipientCompany: 'John Lewis Customer Service',
    recipientCity: 'Manchester',
    hookA: 'achieving above-average NPS and First-Contact-Resolution scores',
    hookB: 'coaching new colleagues during their induction period',
  },
  recruiter: {
    vacancyTitle: 'Senior Talent Acquisition Partner',
    recipientCompany: 'Skyscanner',
    recipientCity: 'Edinburgh',
    hookA: 'sourcing senior software engineers and data professionals',
    hookB: 'reducing time-to-hire through stronger hiring-manager partnership',
  },
};

/**
 * Build a CoverLetterData object from a CV example, using the per-function
 * English letter context. The candidate's name, address, and contact info come
 * from the CV example; the letter body is composed from the hooks plus a
 * generic British-English structure.
 */
export function buildExampleLetter(example: FunctieExample): CoverLetterData {
  const ctx = LETTER_CONTEXTS_EN[example.slug];
  if (!ctx) return createEmptyCoverLetter();

  const now = new Date('2026-05-15').toISOString();
  const greeting = ctx.contactName ? `Dear ${ctx.contactName},` : 'Dear Hiring Manager,';

  const opening = `I am writing to express my strong interest in the ${ctx.vacancyTitle} role at ${ctx.recipientCompany}. The combination of your organisation and this position aligns closely with the direction in which I want to take my career.`;

  const body = `In my current role as ${example.cv.experience[0]?.jobTitle ?? 'professional'}${
    example.cv.experience[0]?.company ? ` at ${example.cv.experience[0].company}` : ''
  }, I have gained experience in ${ctx.hookA}. Alongside that, I actively focus on ${ctx.hookB} — for me that is an essential part of the work. I recognise in the ${ctx.recipientCompany} job advert the way these elements come together.`;

  const closing = `${
    ctx.availability ?? 'I would welcome the opportunity to discuss my application further in person.'
  } You can reach me at ${example.cv.personal.email}${
    example.cv.personal.phone ? ` or on ${example.cv.personal.phone}` : ''
  }.`;

  return {
    id: `example-letter-${example.slug}`,
    createdAt: now,
    updatedAt: now,
    sender: {
      firstName: example.cv.personal.firstName,
      lastName: example.cv.personal.lastName,
      email: example.cv.personal.email,
      phone: example.cv.personal.phone,
      address: example.cv.personal.address || '',
      city: example.cv.personal.city,
      postalCode: example.cv.personal.postalCode || '',
    },
    recipient: {
      contactName: ctx.contactName ?? '',
      contactTitle: '',
      company: ctx.recipientCompany,
      city: ctx.recipientCity,
    },
    vacancyTitle: ctx.vacancyTitle,
    vacancyReference: '',
    date: '2026-05-15',
    letterCity: example.cv.personal.city,
    greeting,
    opening,
    body,
    closing,
    signature: 'Yours sincerely,',
    meta: {
      selectedTemplate: 'modern',
      selectedColorScheme: (example.colorSchemeId as ColorSchemeId) || 'emerald',
    },
  };
}

export function hasLetterContext(slug: string): boolean {
  return slug in LETTER_CONTEXTS_EN;
}

export { LETTER_CONTEXTS_EN };
