import { CoverLetterData, createEmptyCoverLetter } from '@/types/cover-letter';
import { ColorSchemeId } from '@/types/cv';
import { FunctieExample } from '@/lib/cv-examples/types';

/**
 * Per-function letter context for the Danish market. The actual letter body is
 * generated by combining this with the CV example's persona data — so we get
 * realistic letters for every function without hand-writing 20 variants.
 */
interface LetterContext {
  /** Target vacancy title (often slightly different from the candidate's current role) */
  vacancyTitle: string;
  /** Fictional Danish company they're applying to */
  recipientCompany: string;
  recipientCity: string;
  /** Optional contact person */
  contactName?: string;
  /** Hooks to weave into the body — concrete to the function */
  hookA: string;
  hookB: string;
  /** Optional availability statement */
  availability?: string;
}

const LETTER_CONTEXTS_DA: Record<string, LetterContext> = {
  developer: {
    vacancyTitle: 'Senior Backend Engineer',
    recipientCompany: 'Lunar',
    recipientCity: 'Aarhus',
    hookA: 'opbygning af pålidelig betalingsinfrastruktur',
    hookB: 'mentoring af junior-udviklere og bidrag til code review-guidelines',
  },
  verpleegkundige: {
    vacancyTitle: 'Intensivsygeplejerske',
    recipientCompany: 'Rigshospitalet',
    recipientCity: 'København',
    hookA: 'pleje af postoperative patienter efter hjertekirurgi',
    hookB: 'klinisk vejledning af sygeplejestuderende og bidrag til kvalitetsudvikling',
  },
  leraar: {
    vacancyTitle: 'Gymnasielærer i historie',
    recipientCompany: 'Aurehøj Gymnasium',
    recipientCity: 'Gentofte',
    hookA: 'undervisning i historie A i den gymnasiale overbygning',
    hookB: 'klasselærerrollen i 3.g og bidrag til curriculum-udvikling',
  },
  accountant: {
    vacancyTitle: 'Audit Manager Financial Services',
    recipientCompany: 'PwC Danmark',
    recipientCity: 'København',
    hookA: 'ledelse af revisionsopgaver hos banker og forsikringsselskaber',
    hookB: 'coaching af associates mod statsautorisations-eksamen',
  },
  'marketing-manager': {
    vacancyTitle: 'Senior Marketing Manager Demand Gen',
    recipientCompany: 'Pandora',
    recipientCity: 'København',
    hookA: 'sænkning af Customer Acquisition Cost i B2B SaaS',
    hookB: 'ledelse af et team af demand generation-specialister',
  },
  verkoper: {
    vacancyTitle: 'Senior Account Executive Enterprise',
    recipientCompany: 'HubSpot Nordics',
    recipientCity: 'København',
    hookA: 'lukning af multi-stakeholder enterprise deals',
    hookB: 'opbygning af en outbound playbook for en ny niche',
  },
  'office-manager': {
    vacancyTitle: 'Office Manager',
    recipientCompany: 'GN Store Nord',
    recipientCity: 'Ballerup',
    hookA: 'styring af hovedkontorets drift og en tæt direktionskalender',
    hookB: 'onboarding af nye medarbejdere og vendor management',
  },
  projectmanager: {
    vacancyTitle: 'Senior Project Manager Digital Transformation',
    recipientCompany: 'Nordea',
    recipientCity: 'København',
    hookA: 'ledelse af programmer omkring core banking-modernisering',
    hookB: 'styregruppe-ledelse på direktionsniveau',
  },
  stagiair: {
    vacancyTitle: 'Strategy Intern',
    recipientCompany: 'McKinsey & Company',
    recipientCity: 'København',
    hookA: 'min erfaring som formand for en studenterforening med 560 medlemmer',
    hookB: 'mine resultater i case-konkurrencer og mit honors-track',
    availability: 'Tilgængelig for et 5-måneders praktikophold fra februar 2026.',
  },
  consultant: {
    vacancyTitle: 'Engagement Manager',
    recipientCompany: 'Bain & Company',
    recipientCity: 'København',
    hookA: 'ledelse af PMI-projekter og cost transformation-programmer',
    hookB: 'coaching af associates mod forfremmelse',
  },
  'logistiek-medewerker': {
    vacancyTitle: 'Senior lagermedarbejder',
    recipientCompany: 'Maersk',
    recipientCity: 'København',
    hookA: 'at arbejde i højt tempo i distributionscentre med WMS-systemer',
    hookB: 'shift-coach-ansvar og cyklisk varetælling',
  },
  monteur: {
    vacancyTitle: 'VVS-energimontør',
    recipientCompany: 'Kemp & Lauritzen',
    recipientCity: 'København',
    hookA: 'installation af varmeanlæg, varmepumper og hybridsystemer',
    hookB: 'at være første kontaktperson for kunder og kolleger ved regionale opgaver',
  },
  'horeca-medewerker': {
    vacancyTitle: 'Shift Leader Service',
    recipientCompany: 'Restaurant Noma',
    recipientCity: 'København',
    hookA: 'fine dining service på Michelin-niveau',
    hookB: 'vin-pairing-rådgivning og bedjening af international klientel',
  },
  'data-analist': {
    vacancyTitle: 'Senior Data Analyst',
    recipientCompany: 'Maersk',
    recipientCity: 'København',
    hookA: 'opbygning af forecasting-dashboards, som bruges direkte til forretningsbeslutninger',
    hookB: 'A/B-test-analyse og modernisering af data-pipelines via dbt',
  },
  'hr-manager': {
    vacancyTitle: 'HR Manager Nordics',
    recipientCompany: 'LEGO Group',
    recipientCity: 'Billund',
    hookA: 'fuld ownership af HR-cyklussen i scale-ups og mid-market-organisationer',
    hookB: 'målbar reduktion af personaleomsætning gennem onboarding-redesign',
  },
  'verzorgende-ig': {
    vacancyTitle: 'Kontaktperson, demensafsnit',
    recipientCompany: 'OK-Fonden',
    recipientCity: 'Aarhus',
    hookA: 'at være kontaktperson for beboere med demens i små bo-enheder',
    hookB: 'klinisk vejledning af SOSU-elever og bidrag til kvalitetsudvalg',
  },
  designer: {
    vacancyTitle: 'Senior Product Designer',
    recipientCompany: 'Pleo',
    recipientCity: 'København',
    hookA: 'design og ownership af et design system, der bruges af dusinvis af engineers',
    hookB: 'gennemførelse af user research og validering af designbeslutninger med konverteringsdata',
  },
  'financieel-medewerker': {
    vacancyTitle: 'Finansbogholder',
    recipientCompany: 'Coloplast',
    recipientCity: 'Humlebæk',
    hookA: 'komplet debitor- og kreditorbogholderi i mellemstore virksomheder',
    hookB: 'support til årsregnskab og automatisering af fakturahåndtering',
  },
  'klantenservice-medewerker': {
    vacancyTitle: 'Senior Kundeservicemedarbejder',
    recipientCompany: 'Bestseller',
    recipientCity: 'Brande',
    hookA: 'opnåelse af NPS- og First-Contact-Resolution-scores over gennemsnittet',
    hookB: 'coaching af nye kolleger under deres indkøringsperiode',
  },
  recruiter: {
    vacancyTitle: 'Senior Talent Acquisition Partner',
    recipientCompany: 'Novo Nordisk',
    recipientCity: 'Bagsværd',
    hookA: 'sourcing af senior software engineers og data professionals',
    hookB: 'reduktion af time-to-hire gennem stærkere hiring manager-partnership',
  },
};

/**
 * Build a CoverLetterData object from a CV example, using the per-function
 * Danish letter context. The candidate's name, address, and contact info come
 * from the CV example; the letter body is composed from the hooks plus a
 * generic Danish letter structure.
 */
export function buildExampleLetter(example: FunctieExample): CoverLetterData {
  const ctx = LETTER_CONTEXTS_DA[example.slug];
  if (!ctx) return createEmptyCoverLetter();

  const now = new Date('2026-05-15').toISOString();
  const greeting = ctx.contactName ? `Kære ${ctx.contactName},` : 'Kære rekrutterer,';

  const opening = `Jeg skriver for at udtrykke min stærke interesse for stillingen som ${ctx.vacancyTitle} hos ${ctx.recipientCompany}. Kombinationen af jeres virksomhed og denne rolle passer fremragende til den retning, jeg ønsker at videreudvikle min karriere i.`;

  const body = `I min nuværende rolle som ${example.cv.experience[0]?.jobTitle ?? 'fagperson'}${
    example.cv.experience[0]?.company ? ` hos ${example.cv.experience[0].company}` : ''
  } har jeg opbygget omfattende erfaring med ${ctx.hookA}. Derudover engagerer jeg mig aktivt i ${ctx.hookB} — for mig er det en uundværlig del af arbejdet. I stillingsopslaget fra ${ctx.recipientCompany} genkender jeg netop den måde, hvorpå disse elementer går op i en højere enhed.`;

  const closing = `${
    ctx.availability ?? 'Jeg vil meget gerne uddybe min motivation i en personlig samtale.'
  } Du kan kontakte mig på ${example.cv.personal.email}${
    example.cv.personal.phone ? ` eller telefonisk på ${example.cv.personal.phone}` : ''
  }.`;

  return {
    id: `example-letter-${example.slug}`,
    createdAt: now,
    updatedAt: now,
    sender: {
      firstName: example.cv.personal.firstName,
      lastName: example.cv.personal.lastName,
      email: example.cv.personal.email,
      phone: example.cv.personal.phone,
      address: example.cv.personal.address || '',
      city: example.cv.personal.city,
      postalCode: example.cv.personal.postalCode || '',
    },
    recipient: {
      contactName: ctx.contactName ?? '',
      contactTitle: '',
      company: ctx.recipientCompany,
      city: ctx.recipientCity,
    },
    vacancyTitle: ctx.vacancyTitle,
    vacancyReference: '',
    date: '2026-05-15',
    letterCity: example.cv.personal.city,
    greeting,
    opening,
    body,
    closing,
    signature: 'Med venlig hilsen,',
    meta: {
      selectedTemplate: 'modern',
      selectedColorScheme: (example.colorSchemeId as ColorSchemeId) || 'emerald',
    },
  };
}

export function hasLetterContext(slug: string): boolean {
  return slug in LETTER_CONTEXTS_DA;
}

export { LETTER_CONTEXTS_DA };
